### ISSUE TITLE
Add RTL support to ooni.org and explorer.ooni.org

### ISSUE THREAD

**Issue by agrabeli** [ooni/ooni.org#1264]
We now have the OONI Probe user guides and OONI Explorer translated into Persian. There is a need to add RTL support to ooni.org and explorer.ooni.org in order to publish these translations. 

An example of the translation and partly RTL support can be found here: a Farsi translation of the OONI Probe user guides (https://github.com/ooni/ooni.org/pull/1263)

**Comment by moonLight-7k** [comment]
Hello, I am interested in contributing to open source projects and would love to participate in any that you have available. I have experience in web Development and am eager to learn and grow my skills through working on these projects. Please let me know if there are any opportunities for me to get involved, I would greatly appreciate it. Thank you!

**Comment by agrabeli** [comment]
Thank you @moonLight-7k , and apologies for not seeing your comment sooner. We greatly appreciate your interest to contribute to OONI web dev projects! <3 If you're still interested, I'd suggest getting in touch with @majakomel and/or @hellais to discuss further. You can also reach them on the OONI Slack channels (https://slack.ooni.org/).

**Comment by agrabeli** [comment]
The activity of this ticket is done, so I'm closing this ticket.
