### ISSUE TITLE
website: Update Netlify build image 

### ISSUE THREAD

**Issue by akronb** [ooni/ooni.org#1271]
On November 15th, 2022, Netlify will be fully removing support for the Ubuntu 16.04 (Xenial) build image. As I understand, this is current build image for OONI website (maybe only for deploy preview).

More information on this issue:
https://answers.netlify.com/t/please-read-end-of-support-for-xenial-build-image-everything-you-need-to-know/68239

**Comment by hellais** [comment]
I don't see in our netlify config file us setting this version of ubuntu (see: https://github.com/ooni/ooni.org/blob/master/netlify.toml). Where did you see that we are using it?

It seems like nothing broke, so we should be good.

**Comment by akronb** [comment]
Oh, I forgot about that issue. I noticed a warning about this problem in `[the deploy log](https://app.netlify.com/sites/ooni/deploys/6310474032dd760009138e08)`.

You can change it in the Netlify UI, but from what I see, you've already fixed that problem.
