### ISSUE TITLE
Launch Censorship Incident Reporting Platform

### ISSUE THREAD

**Issue by agrabeli** [ooni/ooni.org#1301]
New censorship events frequently emerge worldwide on an ongoing basis, but producing an in-depth report and analysis on each event (in a timely manner) is not easily scale-able. Moreover, rapid response efforts benefit from censorship findings that are easier and quicker to consume.

We therefore aim to create a Censorship Incident Reporting Platform which will **regularly provide short reports with summary information on emergent censorship events based on OONI data and charts**. This will enable journalists and human rights defenders to more easily learn about and respond to censorship events. Over time, the platform will become an archive of known censorship incidents from around the world based on OONI network measurement data. 

In developing this platform, we will ensure that it is complementary to existing efforts. For example, OONI is currently a data partner for the Internet Society (ISOC) Pulse project which provides a timeline of internet shutdowns around the world. This project primarily covers internet outages (based on multiple datasets), while OONI’s Censorship Incident Reporting Platform will cover a broader range of blocking events (such as news media and human rights website blocking) based on OONI data. OONI’s Censorship Incident Reporting Platform will also be different (and complementary) to the Tor Project’s Tor Metrics Timeline, which relies on community members to contribute information about censorship events. Instead, the OONI Censorship Incident Reporting Platform will **regularly publish short reports that provide charts based on aggregate views of OONI data (which journalists and activists can easily use), linking to relevant OONI measurements** (that can serve as evidence of internet censorship), and providing relevant concise interpretation of OONI censorship measurement findings.

**Comment by agrabeli** [comment]
This activity first requires developing the web platform (and any backend work that might be required), before summary reports can be written (by me).

**Comment by agrabeli** [comment]
I have set a tentative timeline on zenhub which probably needs to be adjusted.

**Comment by jbonisteel** [comment]
* email capture requirement was last that popped up - be + fe are done, just needs to be tested
* some PRs need to be reviews/closed - @FedericoCeratto will share links

**Comment by jbonisteel** [comment]
Launched on November 30, 2023
