### ISSUE TITLE
spec: we have a new iteration of the OONI Run v2 spec

### ISSUE THREAD

**Issue by hellais** [ooni/ooni.org#1384]

**Comment by hellais** [comment]
We don't yet have a PR for an update to the spec, we have however documented a fair amount of things on the changes we are looking for as part of the backend API implementation and the following docs:
* https://docs.google.com/document/d/1tsik0DZLOgYHh01RsLWWXp3ZHhHB_C07j8dcaMbGB9M/edit
* https://docs.google.com/document/d/1nR3lwW-BeMCT1h_m5zG9kmvzSv0he5-ZvvLwaxWac8E/edit

**Comment by jbonisteel** [comment]
We need to remove some things that are no longer accurate in the spec

* @FedericoCeratto to update the spec to reflect the api/backend changes 
* We will also review the design to see if other updates are needed

**Comment by bassosimone** [comment]
I committed a small diff clearly flagging which fields of a descriptor are still experimental: https://github.com/ooni/spec/pull/279.

**Comment by jbonisteel** [comment]
@hellais can you review the spec and decide if there is anything else needed?

**Comment by jbonisteel** [comment]
Need to decide if we update spec to be more like the final implementation or the other way around.

**Comment by jbonisteel** [comment]
Closing this, as it is a duplicate - somewhat - of https://github.com/ooni/backend/issues/787
