### ISSUE TITLE
Document the analysis methodology for detecting throttling

### ISSUE THREAD

**Issue by hellais** [ooni/ooni.org#1406]

**Comment by bassosimone** [comment]
I have documented the theory used by the probe to collect data useful to detect throttling (see above).

**Comment by bassosimone** [comment]
I merged https://github.com/ooni/probe-cli/pull/1546, that explains the methodology and the theory we use on the probe side of things. I am not sure whether we also want a backend-side documentation of this. I'll remove myself as an assignee from this issue and assign to @jbonisteel such that she can evaluate this topic and coordinate with other team members.

**Comment by jbonisteel** [comment]
Will close this epic for now since it focuses on the engine side of things.
