### ISSUE TITLE
ooni.org partner page layout is broken on mobile

### ISSUE THREAD

**Issue by sloncocs** [ooni/ooni.org#1408]
The layout of the list of partners is broken on mobile. 

Currently layout of [this page](https://ooni.org/partners) on mobile looks like this: 

![IMAGE 2023-08-14 22:12:16](https://github.com/ooni/ooni.org/assets/16296135/e4cfd1b3-3d36-4cac-96cc-f8c65403de4e)

**Comment by hellais** [comment]
Thanks for bringing this up. I agree this is important to fix. Probably doing something with the responsive breakpoints should suffice, but we need to see what's doable.
