### ISSUE TITLE
Autodetection - complete observation feature extraction (RC stage)

### ISSUE THREAD

**Issue by jbonisteel** [ooni/ooni.org#1448]
This is about adding full support for feature extraction, which includes the updates to the web connectivity datamodel and performing feature extraction on the currently unsupported tests.

Enriching the features extracted as part of the OONI data processing pipeline to facilitate more advanced analysis.

**Comment by hellais** [comment]
We now have an alpha version tagged for this: https://github.com/ooni/data/releases/tag/v5.0.0-alpha.0

**Comment by hellais** [comment]
Since most of the basic tests are now supported I have removed that issue from this epic, since I don't think that's necessary to move forward with a release candidate of the oonipipeline v5.
