### ISSUE TITLE
Richer input: ooni/data powered analysis

### ISSUE THREAD

**Issue by jbonisteel** [ooni/ooni.org#1472]
- [ ] ooni/data: support for processing dnscheck: need to support HTTP/3 measurements;

**Comment by hellais** [comment]
This is basically doing this: https://github.com/ooni/data/issues/39

**Comment by hellais** [comment]
Re: the dnscheck point, I realised it wasn't listed here: https://github.com/ooni/data/issues/32. I added it. It's still a bit unclear if this is about dnscheck or if it's web_connectivity 0.5 (or both)?
