### ISSUE TITLE
Which address should I send emails to? @ooni.org or @openobservatory.org?

### ISSUE THREAD

**Issue by Lanius-collaris** [ooni/ooni.org#1536]
https://ooni.org/ : `contact 𝖆𝖙 openobservatory.org`
https://ooni.org/about/team/ : `arturo 𝖆𝖙 ooni.org`

**Comment by bassosimone** [comment]
The two domains are aliases of each other. IIRC, `@openobservatory.org` is the one for which we have PGP. So, I would use `@openobservatory.org` especially if you need to use PGP.
