### ISSUE TITLE
Telegram nettest description still claims to test web.telegram.org

### ISSUE THREAD

**Issue by Em4E** [ooni/ooni.org#1600]
https://github.com/ooni/ooni.org/blob/a71fd3d7a8829d7d02d4dd1f9c17625078cd6f77/content/nettest/telegram.md talks about measuring web.telegram.org, but according to https://github.com/ooni/probe/issues/2382 and https://github.com/ooni/spec/pull/269 that no longer happens.

**Comment by hellais** [comment]
Thanks for reporting this, it's fixed in: https://github.com/ooni/ooni.org/commit/65b497d33ab31eca9ba72002821733b8776592f9
