### ISSUE TITLE
Change license to CC-BY-SA

### ISSUE THREAD

**Issue by hellais** [ooni/ooni.org#161]
We should add a footer to every page with the CC-BY-SA notice.
See: https://github.com/OpenObservatory/legal

**Comment by darkk** [comment]
The trigger was inability to re-publish translation from https://cripto.cat/blog/censura-internet-referendum
See also hermes-diactoros/cripto.cat.grav#1

**Comment by elioqoshi** [comment]
I suppose we won't do a NC license right? Because that would be too restrictive.

**Comment by bassosimone** [comment]
> Because that would be too restrictive.
Totally agree!

**Comment by hellais** [comment]
Correct. See: https://github.com/OpenObservatory/legal?files=1

**Comment by hellais** [comment]
This is done.
