### ISSUE TITLE
New Logo for Open Culture Foundation

### ISSUE THREAD

**Issue by toomore** [ooni/ooni.org#1610]
Hi OONI team,

We have new logo from this year, could you please help us to update the logo image, thanks.

- Source: https://ocf.tw/mediakit/logo.png
- Partners Page: https://ooni.org/partners/open-culture-foundation/

![Open Culture Foundation](https://ocf.tw/mediakit/logo.png)

**Comment by sloncocs** [comment]
Thanks @toomore! I updated the logo with this PR: #1611, it should be already visible on the website

**Comment by toomore** [comment]
@sloncocs Thank you!
