### ISSUE TITLE
Specify canonical URL for mirrors

### ISSUE THREAD

**Issue by darkk** [ooni/ooni.org#231]
The website has four mirrors listed in README.md. Google Search serves documents both from `ooni.io` and `ooni.torproject.org`
- [ ] define the canonical domain for URLs: ooni.torproject.org or ooni.io
- [ ] add [markup](https://support.google.com/webmasters/answer/139066) to codify it

**Comment by hellais** [comment]
This is a good point. I think we should, for consistency and brevity, opt for making `ooni.io` the canonical URL or our homepage.

We probably want to also do some subset of this: https://github.com/ooni/sysadmin/issues/224, before doing it.

**Comment by hellais** [comment]
The canonical website is now ooni.org. Everything redirects to that. Closing.
