### ISSUE TITLE
is that possible to create my own TOR network on the LAN ??

### ISSUE THREAD

**Issue by VtpVlan-oo7** [ooni/ooni.org#237]
![screenshot from 2018-10-29 16-23-07](https://user-images.githubusercontent.com/31241756/47646058-bef46600-db98-11e8-8c2d-3a693c8c1668.png)
![screenshot from 2018-10-29 16-22-54](https://user-images.githubusercontent.com/31241756/47646088-d6cbea00-db98-11e8-9888-c83669d2ef78.png)
![screenshot from 2018-10-29 16-23-02](https://user-images.githubusercontent.com/31241756/47646095-db909e00-db98-11e8-8150-7da16f1f8b86.png)
![screenshot from 2018-10-29 16-22-42](https://user-images.githubusercontent.com/31241756/47646099-dfbcbb80-db98-11e8-9890-20374334dd63.png)

**Comment by hellais** [comment]
You may want to check out: https://support.torproject.org.

Closing this as it's unrelated to OONI.
