### ISSUE TITLE
Terminate legal@ooni.io

### ISSUE THREAD

**Issue by agrabeli** [ooni/ooni.org#256]
We're not in a position to offer legal advice, so I propose we terminate the legal@ooni.io email address.

However, it seems that we're linking to it somewhere, since some people are finding this email address and reaching out to us, seeking legal advice. 

We therefore first need to identify the web pages that mention legal@ooni.io, edit those pages (to delete the email address), and then proceed with terminating this email address.

**Comment by hellais** [comment]
We don't refer to this anymore in any place. Closing this issue as done.
