### ISSUE TITLE
Create Partnership Page

### ISSUE THREAD

**Issue by agrabeli** [ooni/ooni.org#273]
The new OONI Partnership Page would communicate:

* What is the OONI Partnership Program
* Who are OONI partners (i.e. which organizations)
* Which countries around the world are covered by OONI partnerships
* How OONI partners use OONI Probe and OONI data as part of their work

To this end, I propose that a possible layout for the new OONI Partnership page is the following:

* Write a summary explaining what the OONI Partnership Program is and linking to this page (which provides detailed information): https://ooni.io/get-involved/partnership-program/

* Include a **map** which highlights the countries we have partnerships in => As a MVP, this map could for starters be static, just highlighting the countries we have partnerships in. In the future (when dev resources permit), we could potentially include an interactive map where not only are countries highlighted, but when you hover over a highlighted country, you get that country's partner (their logo and info about their work). 

* **List all of the partners**, and categorize them based on geographic regions (Latin America, Africa, Asia, Global). In the listing, include their **logos & links to their websites**. 

* Include a "highlights" section (it won't be called that), where we **showcase some partner projects that use OONI Probe and OONI data**. As an example, we can showcase Sinar Project's Southeast Asia Dashboard (https://sinarproject.org/digital-rights/human-rights-internet-censorship-dashboards), the research reports published by the Digital Security Lab of Ukraine, the projects of our Venezuelan partners, etc.

* In the future, it would be cool to embed a 2-minute **video** on this page which features our partners, where they tell the world how they lead censorship measurement research and advocacy in their communities.

**Comment by hellais** [comment]
I did another iteration of this page and I would say it's now ready for review by @agrabeli .

It is still missing some copy, we can perhaps create another dedicated issue for that.

**Comment by hellais** [comment]
This has been done.
