### ISSUE TITLE
https://www.ooni.io is giving certificate errors

### ISSUE THREAD

**Issue by p1g30n** [ooni/ooni.org#291]
Visiting https://www.ooni.io gives me `SSL_ERROR_BAD_CERT_DOMAIN` with a certificate that seems only valid for netlify.com and its subdomains.

**Comment by xhdix** [comment]
Maybe @hellais should delete and re-add the www alias in Netlify.
And there is some other tips :
https://docs.netlify.com/domains-https/troubleshooting-tips

**Comment by hellais** [comment]
It turns out that we didn't have the www in the certificate at all. I have re-added it.

**Comment by xhdix** [comment]
@hellais the https://github.com/ooni/ooni.org/commit/9c0edd4ca7e7458957cda71ea07a8da6b0675a1c wasn't the best idea.
As @p1g30n  said https://github.com/ooni/ooni.org/pull/315#issuecomment-566756808 we must redirect **to** the www. (This is the first thing Google wants)
Also the answer of `dig ooni.org` still does not equal to `dig www.ooni.org`.

**Comment by p1g30n** [comment]
@xhdix I wasn't sure about the best redirect solution when I made that comment, I just saw that https://www.ooni.io didn't redirect to https://ooni.io , which also meant it wouldn't finally redirect to https://ooni.org.
Do you know wether Google prefers less 301s (as with the current solution) or more accurate mapping of domains (e.g. https://www.ooni.io -> https://www.ooni.org -> https://ooni.org) ?

A third option would be that all domains first undo their www. subdomain and then redirect to https://ooni.org (as in https://www.ooni.io -> https://ooni.io -> https://ooni.org)

I'm unclear what the best option would be

**Comment by hellais** [comment]
Hum, does this mean we must make the canonical version of our website be `https://www.ooni.org`?

I have never been a big fan of the `www` in front of domain names for websites, but mostly just for aesthetics. If making the canonical version of our site be `www.ooni.org` boosts our SEO, we should do it.

> Also the answer of dig ooni.org still does not equal to dig www.ooni.org.

The reason for this is that we can't put a CNAME on the apex of the domain, so we have to use the IP of one of the netlify hosts.

Netlify also suggest using www as the canonical version of your website, see: https://www.netlify.com/blog/2017/02/28/to-www-or-not-www/.

What do you folks think, should we `www` or not `www`?

**Comment by xhdix** [comment]
@hellais If you check Google Webmaster Tools, all requests should be redirected to  `https://www.ooni.org`

**Comment by p1g30n** [comment]
@hellais I'm not aware that Google has any preference towards www. or not. I just know from past projects that it does prefer certain redirect chains to others but it's too long ago to remember the specifics. I'll try to find a comprehensive resource on it.

**Comment by hellais** [comment]
> If you check Google Webmaster Tools, all requests should be redirected to https://www.ooni.org

Where do I check this?

**Comment by hellais** [comment]
BTW if you folks give me a google email (on slack) I can add you as a user to the ooni.org|io|torproject.org resources so you can check these things out.
I am a bit of a SEO n00b, so I don't really know where to look for stuff.

**Comment by p1g30n** [comment]
@hellais this might be of interest https://support.google.com/webmasters/answer/9370220?hl=en

**Comment by xhdix** [comment]
I couldn't find any proof of my claim except:
> In search results most pages indexed are the www. version but some e.g. homepage arent. When I look at both versions on search console most coverage relates to www. versions of the page because I believe Google has selected it as canonical. 
https://support.google.com/webmasters/thread/15013153?hl=en

Therefore, there is no must.

**Comment by p1g30n** [comment]
> I couldn't find any proof of my claim except:
> 
> > In search results most pages indexed are the [www](http://www). version but some e.g. homepage arent. When I look at both versions on search console most coverage relates to [www](http://www). versions of the page because I believe Google has selected it as canonical.
> > https://support.google.com/webmasters/thread/15013153?hl=en
> 
> Therefore, there is no must.

That would align with my spotty knowledge of it. Canonical with www seems weird though since it's specified without on ooni.org. But sometimes these sort of changes take a while to propagate. I will have time tomorrow to have a look into webmaster tools, if it's really the case maybe there's a way to change it in there.

**Comment by p1g30n** [comment]
> @xhdix I wasn't sure about the best redirect solution when I made that comment, I just saw that https://www.ooni.io didn't redirect to https://ooni.io , which also meant it wouldn't finally redirect to https://ooni.org.
> Do you know wether Google prefers less 301s (as with the current solution) or more accurate mapping of domains (e.g. https://www.ooni.io -> https://www.ooni.org -> https://ooni.org) ?
> 
> A third option would be that all domains first undo their [www](http://www). subdomain and then redirect to https://ooni.org (as in https://www.ooni.io -> https://ooni.io -> https://ooni.org)
> 
> I'm unclear what the best option would be

@xhdix do you have any info or resource on which of the above redirect chains would be best suited for keeping pagerank?

**Comment by xhdix** [comment]
Since there is no index from www, we can redirect directly to the final URL.
e.g. https://www.ooni.io -> https://www.ooni.org || https://ooni.org
