### ISSUE TITLE
Improve SEO of ooni.org

### ISSUE THREAD

**Issue by xhdix** [ooni/ooni.org#314]
Due to the HUGO limitation I don't know how much SEO can be done.
(It is said that search engine bots are blind. They follow braille(HTML) lines to increase their understanding of each page.)
Here are some things to get started:

**High priority:**

- [x] Change title to: `<title> {{.Title}} - OONI </title>`  (or: `{{if .IsHome}}{{ $.Site.Title }}{{else}}{{.Title}}{{end}}` )
- [x] Each page should have a unique title and description. (Especially in the meta tag -- OpenGraph and Twitter) . First we need to add the `description` value in all the posts beside the `title`. Next, change the `head.html` file as the `title` :point_up_2: .

~Images must have a relevant name. (Not just the name in the image. Google can read the texts in the images itself). Something like `Image-title-Post-title-Time.jpg` or more. (not jpeg or png : https://web.dev/uses-webp-images/ )~
Moved to: https://github.com/ooni/ooni.org/issues/390

~Set `alt = "Image description"` for images: `![Image-description](/brief-image-description.png)`~
Moved to: https://github.com/ooni/ooni.org/issues/390

- [x] Add `sitemap.xml` : https://search.google.com/search-console/sitemaps?resource_id=sc-domain%3Aooni.org&hl=en : https://support.google.com/webmasters/answer/7451001?hl=en

- [x] Add `robots.txt` : https://support.google.com/webmasters/answer/6062608?hl=en

- [x] Redirect to the new address via `HTTP 301` . Two addresses with the same content are the worst. But OONI has three (or more) addresses ( `ooni.torproject.org` - `ooni.io` - `ooni.org` )  . Only one address must be used. 

**Medium priority:**

~On all pages, the main title should be in the `<h1>` tag.~
Moved to: https://github.com/ooni/ooni.org/issues/391

- [x] Avoid having multiple css files as much as possible. (Also js files) : https://gohugo.io/hugo-pipes/minification/ : https://web.dev/critical-request-chains/

~More favicon should be added: https://realfavicongenerator.net/favicon_checker?protocol=http&site=ooni.org#.Xfdm5FVfjIc~
Moved to: https://github.com/ooni/ooni.org/issues/392

- [x] Display image in link preview: https://discourse.gohugo.io/t/display-first-image-in-post-in-link-preview/10541/6

~Fix `Mobile Usability` issues : https://search.google.com/search-console/mobile-usability?resource_id=sc-domain%3Aooni.org&hl=en~
~ fix `Speed` issues : https://search.google.com/search-console/speed?resource_id=sc-domain%3Aooni.org&hl=en ( e.g. https://developers.google.com/speed/pagespeed/insights/?url=https%3A%2F%2Fooni.org%2Fpost%2F2019-measure-blocking-lgbtqi-sites%2F&tab=mobile&hl=en )~
~Fix coverage `Excluded` issues : https://search.google.com/search-console/index?resource_id=sc-domain%3Aooni.org&hl=en~
Moved to: https://github.com/ooni/ooni.org/issues/393

**Low priority :** 

~Redirect other sub-domains like `slack.ooni.io` and `slack.openobservatory.org` to the new address.~
Moved to: https://github.com/ooni/backend/issues/336

~ Add `Spec` pages to ooni.org. (Just for indexing)~
Duplicate of: https://github.com/ooni/ooni.org/issues/235

~Add Wikipedia pages.~
Moved to: https://github.com/ooni/ooni.org/issues/394

~Add keywords/tags to pages~
Moved to: https://github.com/ooni/ooni.org/issues/395

~Make OONI pretty for Google (Software App, Sitelinks Searchbox, Q&A, Logo, Dataset, Article) : https://developers.google.com/search/docs/guides/search-gallery ~
Moved to: https://github.com/ooni/ooni.org/issues/396

- [x] Add `Q&A` page. 

( I found a good article: https://support.google.com/webmasters/answer/7451184 )

**Comment by p1g30n** [comment]
Backlinks would be another factor, the canonical domain name is now ooni.org, if a lot of links are still pointing to ooni.torproject.org or different domain names there might be some wasted potential, although I'm not sure if google isn't elaborate enough to let those old links count for ranking on the new domain.

**Comment by xhdix** [comment]
@p1g30n If the old URLs are properly redirected to the new address, (301 is recommended*) some old page rank will be moved to the new page.

( * ooni.torproject.org/post/2019-censorship => ooni.org/post/2019-censorship || ooni.org/post/something-else.html )

**Comment by p1g30n** [comment]
@xhdix what if the link does not redirect (as in the case of https://ooni.torproject.org/ ) but has ooni.org set as canonical?

**Comment by xhdix** [comment]
@p1g30n Not a good situation. Google AI will decide. what is certainly happening is the division of rankings between all versions of the site.
With some search I realized that the `noindex` meta tag can be used (But its rank does not move to the new site) : 

> Syndicate carefully: If you syndicate your content on other sites, Google will always show the version we think is most appropriate for users in each given search, which may or may not be the version you'd prefer. However, it is helpful to ensure that each site on which your content is syndicated includes a link back to your original article. You can also ask those who use your syndicated material to use the noindex meta tag to prevent search engines from indexing their version of the content.

https://support.google.com/webmasters/answer/66359?hl=en

**Comment by hellais** [comment]
We can do the 301 redirect from ooni.io and ooni.torproject.org to ooni.org pretty easily and it should not break anything.

Actually for ooni.io we should already be doing it: https://github.com/ooni/ooni.org/blob/master/netlify.toml#L10, though I think that due to a bad rule in there it's not happening for the homepage, but only for subpages.

**Comment by hellais** [comment]
I am very glad you folks have brought this up.

I think our current SEO situation is pretty bad.

![Screenshot 2019-12-17 at 12 58 10](https://user-images.githubusercontent.com/424620/70993766-fa1f6480-20cc-11ea-8412-8dff851ad2d1.png)

**Comment by xhdix** [comment]
> When we do the redirect, we should also monitor access logs to ensure we aren't getting a higher rate of 404 errors (we can do that with matomo).

@hellais It's a good time to get help from Google :stuck_out_tongue: : 
https://www.google.com/webmasters/

You need to add all three sites.
(They give you an ID for all your sites.)

**Comment by hellais** [comment]
@xhdix yeah we have set it up in there for ooni.org and ooni.io. It's not simple to add ooni.torproject.org because we don't control the DNS of it.

Is there some specific bits in there that you think would be useful to better understand the situation?

**Comment by xhdix** [comment]
Let me check the redirect via `meta` tag.

**Comment by xhdix** [comment]
Here are some serious problems that need to be addressed.
![image](https://user-images.githubusercontent.com/12384263/72649873-d7b08d80-398f-11ea-92f6-06b1363abc11.png)
But before all of this, items 2, 3 and 4 must be done in `High priority` section.
:fire: _First we need to add the `description` value in all the posts beside the `title`._  + in all the pages
![image](https://user-images.githubusercontent.com/12384263/72650405-7be70400-3991-11ea-9f57-47bf6fb96b9c.png)

**Comment by hellais** [comment]
I wonder if we should actually make this an epic, as it has many items in it. In any case I didn't do any progress on this, moving it to the next sprint.

**Comment by hellais** [comment]
Thanks for putting together all of this checklist @xhdix. It's super helpful!

I have migrated all these issues to their own dedicated issues so we can track them separately. 

They have all been attached to the Improve the OONI website zenhub epic: https://app.zenhub.com/workspaces/sprint-planning-5dfa4b7355438f7e86c80e5a/issues/ooni/ooni.org/329.

I am going to close this issue and resume the work on this in the other issues.
