### ISSUE TITLE
Make OONI Probe’s reporting logic more resilient to censorship

### ISSUE THREAD

**Issue by hellais** [ooni/ooni.org#320]
Add logic for detecting that some circumvention strategy should be used for speaking to OONI backends.
Discover when OONI testing backend infrastructure is being blocked in a particular country or network.
Support submitting measurements using circumvention techniques (e.g., alternative host, using pluggable transports, Psiphon, etc.)

**Comment by bassosimone** [comment]
We discussed some aspects related to this during the last backend meeting:

* Using sentry to log exceptions if we cannot submit reports

* Sometimes randomly selecting Psiphon (or Tor) to submit is fine

* Collect of OONI measurements on a machine which has a tor bridge which helps us for evasion, but also circumvention

* This is a way to help the project is to donate bandwidth a bridge

* Engage the technical community (include people in Tor) to run a pluggable transport bridge server which forwards traffic to OONI probe service for circumventing blocking, but also to measure the blocking of pluggable transports and their performance

**Comment by hellais** [comment]
We are going to implement perhaps not all the solutions, but just a few. Work on this is also being done as part of other milestones. cc @bassosimone
