### ISSUE TITLE
Data analysis: Blocking of LGBTQI sites in MENA region

### ISSUE THREAD

**Issue by agrabeli** [ooni/ooni.org#330]
This analysis involves analyzing all Web Connectivity measurements ever collected from the following countries:

* Egypt
* Lebanon
* Tunisia
* Iran
* Morocco
* Sudan (not a MENA country, but it was requested as part of this analysis)

More specifically, we need to only analyze measurements that have the **LGBT** category code (https://github.com/citizenlab/test-lists/blob/master/lists/00-LEGEND-new_category_codes.csv) from the Citizen Lab test lists (https://github.com/citizenlab/test-lists/tree/master/lists).

The analysis should produce a **CSV file** that contains the (LGBT-categorized) URLs that presented anomalies, the type of anomaly that each URL presented (HTTP-diff, HTTP-failure, DNS, TCP/IP), ASNs, date & time of anomalous measurement, their respective OONI Explorer measurements, etc. 

This analysis can be done as part of the global analysis done for this ticket: https://github.com/ooni/pipeline/issues/261

**Comment by hellais** [comment]
This is no longer relevant. We can re-open if needed.
