### ISSUE TITLE
Perform data analysis of India websites for OONI fellow

### ISSUE THREAD

**Issue by hellais** [ooni/ooni.org#331]
This entails looking at web_connectivity measurements from a specific set of report_ids and looking at the blocking of websites depending on the target region.

**Comment by hellais** [comment]
I have provided @agrabeli with some initial data analysis which looks at measurements from India which include a blockpage.

As part of doing this research I ended up finding the simhash metric quite useful to mine data without needing to reprocess it.

**Comment by anadahz** [comment]
@hellais Do you have any scripts or notes from that data analysis?

**Comment by hellais** [comment]
@anadahz it's nothing too interesting and quite similar to the other scripts I have shared with you in the past too.

Anyways here is the, quite messy, jupyter notebook: https://gist.github.com/hellais/3dedc508a2fbdf2ac51906442519bc7a.
