### ISSUE TITLE
Create page for the tor test description

### ISSUE THREAD

**Issue by hellais** [ooni/ooni.org#335]
We currently don't have a page for the new Tor test at https://ooni.org/nettest/tor.

It should be written based on this spec: https://github.com/ooni/spec/blob/master/nettests/ts-023-tor.md

**Comment by hellais** [comment]
@agrabeli will be picking the brain of @bassosimone to learn how this test works.

**Comment by agrabeli** [comment]
This is done here: https://github.com/ooni/ooni.org/pull/451
