### ISSUE TITLE
Switch all our testing over to github actions

### ISSUE THREAD

**Issue by hellais** [ooni/ooni.org#382]
Currently we use a mixture of various platforms for doing testing.

After much frustration with the travis.org|.com|github marketplace fiasco I decide to switch ooni.org to circle-ci.

I hear @bassosimone is currently investigating github actions as a replacement.

We should take note of what works well or not so well in each of these platforms and eventually consider consolidating CI into one system if possible.

**Comment by bassosimone** [comment]
Migrated netx to GitHub actions very easily here: https://github.com/ooni/netx/pull/151. It occurs to me that one can define many separate actions. This means that, potentially, we can have a multi source repository where, e.g., Go tests and Python tests run in parallel.

**Comment by hellais** [comment]
I think that rather than doing all of this in one go, we should do this incrementally one repo at a time.

I have converted this issue into an epic and I am going to drop it from the sprint.

**Comment by hellais** [comment]
We don't need to take a one-size fits all approach, but we can rather use a mixture of github actions circle CI.
