### ISSUE TITLE
Create a donate page for OONI

### ISSUE THREAD

**Issue by hellais** [ooni/ooni.org#400]
We should have a page where people can donate to OONI.

Some inspiration for a possible donate page could be: 
https://donate.mozilla.org/en-GB/
https://donate.torproject.org/
https://supporters.eff.org/donate/join-4

OONI Style Guide: https://design.ooni.io/

**Comment by hellais** [comment]
We could also introduce donation tiers for sponsors which want to provide a substantial yearly donation and also be featured on our website.

For example we could display on the donation page that for more than 10k/y you can have your logo and link features on our sponsors page.

**Comment by hellais** [comment]
We should also consider doing an open collective to support receiving tax deductible donations from US donors: https://opencollective.com/

**Comment by hellais** [comment]
We now have an OpenCollective account: https://opencollective.com/ooni

**Comment by Vivsss** [comment]
I'm pushing a first structural sketch of the new Donate page on git :)

**Comment by hellais** [comment]
This is done. It just needs to be reviewed for copy by @agrabeli
