### ISSUE TITLE
Create draft IFF Internet Measuremement Village agenda

### ISSUE THREAD

**Issue by agrabeli** [ooni/ooni.org#409]
We're co-organizing the Internet Measurement Village at the Internet Freedom Festival (IFF) this year. Based on the great session ideas proposed by community members, I'll be creating a draft agenda for our village (and following-up with community members to explore opportunities for merging sessions and refactoring session ideas).

**Comment by darkk** [comment]
FYI: [IFF 2020 was cancelled](https://internetfreedomfestival.org/wiki/index.php/Cancellation_of_the_2020_Internet_Freedom_Festival). That was announced [an hour ago](https://twitter.com/InternetFF/status/1234881163996618755).
