### ISSUE TITLE
Update the install page with up to date instructions

### ISSUE THREAD

**Issue by hellais** [ooni/ooni.org#429]
Currently the desktop install page (as several people have already pointed out since a while: https://github.com/ooni/ooni.org/issues/306) is a bit of a mess.

I did a mockup for how we could improve it some time ago:

![InstallPageRevamp](https://user-images.githubusercontent.com/424620/76301193-2575b200-62be-11ea-9fe6-b62c927d8fd8.png)

We should also consider just fixing up the obvious errors in it in the immediate short term even prior to implement the nice mockup mentioned above.

**Comment by hellais** [comment]
Below are updated mockups for the various pages we need.

The idea is that users when they visit https://ooni.org/install will land on:
![Install Landing](https://user-images.githubusercontent.com/424620/76893214-45900d00-688c-11ea-9fa0-1cb8225fdb1c.png)

When they choose Desktop or Mobile they will land on the relevant page which has a phone or a desktop.
![Install Mobile](https://user-images.githubusercontent.com/424620/76893108-14174180-688c-11ea-988b-a84c9bacf799.png)

![Install Desktop](https://user-images.githubusercontent.com/424620/76893125-1aa5b900-688c-11ea-8d9e-a8fd9e98dac2.png)

When they are on the Desktop page and they click other platforms, then the modal will appear.

![Install Other Platforms](https://user-images.githubusercontent.com/424620/76893120-19748c00-688c-11ea-96e0-3446045fbfa7.png)

If they choose CLI they will end up on https://github.com/ooni/probe-cli.

Feedback from folks like @holantonela or others is very welcome :)

The copy is just a placeholder, it still needs some work on it from @agrabeli.

**Comment by holantonela** [comment]
hey, it looks great! do you have it live somewhere so I can make in-context comments?

**Comment by hellais** [comment]
Yes it should be possible to that here:
https://sketch.cloud/s/JOAde/a/0EV7x0
https://sketch.cloud/s/JOAde/a/l0ZGrO
https://sketch.cloud/s/JOAde/a/1DYPLy
https://sketch.cloud/s/JOAde/a/pReKAp

**Comment by holantonela** [comment]
Thank you! just general comments were allowed, so I copy and pasted it in Marvel.

https://marvelapp.com/22374246/screen/67352108
https://marvelapp.com/22374246/screen/67352143

I think you need some titles [here](
https://user-images.githubusercontent.com/424620/76893120-19748c00-688c-11ea-96e0-3446045fbfa7.png
). Something like "For desktop" and "For mobile" could help.

The flow is good. You can easily estimate where users are coming from and offer that build package short-coming the download path.

**Comment by hellais** [comment]
@holantonela thank you so much for your feedback!

Based on it I have made another iteration on the designs:

https://sketch.cloud/s/JOAde/a/0EV7x0
https://sketch.cloud/s/JOAde/a/1DYPLy
https://sketch.cloud/s/JOAde/a/pReKAp

I didn't update the mobile install page as once we finalise it for desktop then it's easy to translate it to mobile.

I have some questions WRT to a few comments:

> Let's align these two columns. You can still keep the background floating on the right side.

What do you mean exactly by this?

> You can use a dark background to blend with the terminal background. It will look nice.

I tried this and I think it's cool, though I am a little bit worried about the contrast of the text. What do you think?

> If we add some gradients to this icon's background?

Based on your suggestion I tried an even more radical experiment and added gradient colors which match with the test group colors.
I think it looks quite nice, though maybe some other solution can also be explored.

What sort of gradient did you have in mind when you suggested it?

**Comment by SaptakS** [comment]
@hellais since the updated designs are not vastly different, I am continuing with the implementation of mobile and desktop page. I will implement all the updates and changes in landing page after that. Is that okay?

**Comment by hellais** [comment]
>  I am continuing with the implementation of mobile and desktop page. I will implement all the updates and changes in landing page after that. Is that okay

Yes that makes sense. I think most of the changes we are discussing are going to be either in the graphical assets which I will export an updated version for you or in some padding or minor layout tweaks we can do in the code directly.

**Comment by hellais** [comment]
We were discussing with @SaptakS on slack about how we will set the content of the primary action button which says "Download OONI Probe for Windows".

I mentioned that since our website is static this should be done using client-side JS logic, yet we also need to handle the case in which JS is disabled (for example in the case of Tor Browser high security settings).

In light of this new requirement I think we should look into dropping the modal for displaying all the possible options and rather opt for having a dedicated page where we list all the possible install methods.

The client side detection logic can therefore be a "fast path" when the users browser supports it in light of JS support, but not a requirement.

**Comment by holantonela** [comment]
We got a long discussion around this problem when working with tpo.org/download. Yes, the JS sniffing is a fast path, but you should support no-js users.

After hellais invited me to the sketch project, I've made small adjustments and fixed some margins. Feel free to download the iterated version here:
https://sketch.cloud/s/5z4Dy/v/4oO9RZ

I'm happy to review the implementation once is in a review shape.

**Comment by timepigeon** [comment]
Not sure if relevant as I'm not aware of a non-JS OS-detection logic but when it comes to modals there are ways to trigger and display them using pure CSS, e.g. https://drublic.github.io/css-modal/

**Comment by SaptakS** [comment]
@timepigeon Yes. I am aware of that. I have actually written CSS modals before in different projects where it was an absolute necessity. So as I and @hellais discussed we would try and see if we can avoid using modals and still make things work.

**Comment by hellais** [comment]
Here is the latest mock we came up with @holantonela (sorry for the plethora of sketch cloud links): https://sketch.cloud/s/3jJew/v/RymWgx/

I also attach a png version of them for ease of consultation:
![Install all platforms](https://user-images.githubusercontent.com/424620/77575517-f1140f80-6ed3-11ea-8c45-24c7107d2c1a.png)
![Install Desktop No Javascript](https://user-images.githubusercontent.com/424620/77575519-f2453c80-6ed3-11ea-9764-b39539b5df0c.png)
![Install Desktop](https://user-images.githubusercontent.com/424620/77575521-f2ddd300-6ed3-11ea-964d-d6e36da182b6.png)
![Install Landing](https://user-images.githubusercontent.com/424620/77575523-f3766980-6ed3-11ea-8b51-0c9eae090616.png)
![Install Mobile Responsive](https://user-images.githubusercontent.com/424620/77575525-f3766980-6ed3-11ea-9ea6-e14cf119ebf6.png)
![Install Mobile](https://user-images.githubusercontent.com/424620/77575527-f40f0000-6ed3-11ea-8e93-92a32a301f74.png)

**Comment by hellais** [comment]
This has been implemented and deployed! Thanks to everyone for the help on this!
