### ISSUE TITLE
Data analysis for LGBTQI research report

### ISSUE THREAD

**Issue by agrabeli** [ooni/ooni.org#437]
As part of our research on the blocking of LGBTQI sites around the world, @hellais previously performed data analysis, with the time range ending around December 2019 (if I am not mistaken). 

As part of that analysis, the blocking of LGBTQI sites was confirmed in the following 5 countries (where blockpages are served and were detected as part of the analysis):

1. Saudi Arabia
2. Iran
3. United Arab Emirates
4. Russia
5. Malaysia

Based on this preliminary analysis, we have decided to limit the scope of the initial research report to the above 5 countries, while adding **Indonesia** to the list as well, because we have confirmed the blocking of LGBTQI sites there in the past (see: https://ooni.org/post/indonesia-internet-censorship/#lgbt). 

To proceed with this research, the following data analysis support would be appreciated:

1. Analyze Web Connectivity measurements from **Indonesia** to identify the blocking of LGBTQI sites
2. Perform this analysis for all 6 countries to also include the **most recent measurements from 2020** (post December 2019, which is was when the preliminary analysis ended).

**Comment by hellais** [comment]
The final list of countries is:

* Saudi Arabia (SA)
* Iran (IR)
* United Arab Emirates (AE)
* Russia (RU)
* Malaysia (MY)
* Indonesia (ID)

Country codes are: `["SA", "IR", "AE", "RU", "MY", "ID"]`

**Comment by hellais** [comment]
I have finished the OONI side of things here. There may be some follow up work, but we shall document that as new issues.
