### ISSUE TITLE
Formatting of OONI Probe: Installation guide

### ISSUE THREAD

**Issue by reedy** [ooni/ooni.org#450]
Hello!

I've noticed the webpage output of https://github.com/ooni/ooni.org/blob/master/content/install/ooniprobe.md at https://ooni.org/install/ooniprobe#running-ooni-probe-from-a-virtual-machine is pretty hard to read in some sections, specifically "Installing OONI Probe" and "Running OONI Probe"

Can we do something to improve it? :) It looks alright on the preview page on github

I don't know if it's a problem with the source, or if there's some sort of transform in between that has broken it

https://ooni.org/install/ooniprobe#running-ooni-probe
<img width="1109" alt="Screenshot 2020-03-25 at 20 55 58" src="https://user-images.githubusercontent.com/67615/77584636-10fb0180-6edb-11ea-8df0-620d5037c672.png">
https://ooni.org/install/ooniprobe#installing-ooni-probe
<img width="1090" alt="Screenshot 2020-03-25 at 20 56 05" src="https://user-images.githubusercontent.com/67615/77584642-135d5b80-6edb-11ea-8c08-6ab08bee6d41.png">

**Comment by hellais** [comment]
Hi!

Thanks for reporting this issue!

We are indeed aware of it (see: https://github.com/ooni/ooni.org/issues/306) and are working on updating the install page with the most up to date information leading to the upcoming OONI Probe Desktop app release, see: https://github.com/ooni/ooni.org/issues/429.

This is being implemented as part of https://github.com/ooni/ooni.org/pull/446
