### ISSUE TITLE
Analyze MM Web Connectivity measurements from the last month

### ISSUE THREAD

**Issue by agrabeli** [ooni/ooni.org#453]
An OTF Information Controls Fellow is investigating internet censorship in Myanmar through the use of OONI Probe.

Through their OONI Probe testing, they have come across many URLs that are flagged as "likely blocked", many of which would make for very important and interesting advocacy cases if indeed confirmed to be blocked.

They have therefore requested that we inform them which websites are blocked (or most likely blocked) based on most recent testing in Myanmar.

Data analysis requirements:

* Measurements: Web Connectivity
* Country code: MM
* Date range: 2020-03-01 to most recent

Data analysis outputs:

* CSV file containing links to OONI Explorer measurements for blocked sites (as well as probe_asn, date_and_time_of_measurement, etc.)

* Graph illustrating the blocking of sites across ASNs in Myanmar (probably a good idea to add the OONI logo to this chart)

It would be helpful if this were done during the **first week of April** in order to support local advocacy efforts in Myanmar.

**Comment by hellais** [comment]
This has been done.
