### ISSUE TITLE
Interview community members -- OONI Run Usability Study

### ISSUE THREAD

**Issue by agrabeli** [ooni/ooni.org#463]
I'll be interviewing community members during this sprint to collect their feedback for the improvement of OONI Run.

This is related to https://github.com/ooni/ooni.org/issues/462.

**Comment by agrabeli** [comment]
This is done. I interviewed 14 community members.

**Comment by agrabeli** [comment]
I have re-opened this ticket because 2 more interviews have been scheduled for the week of 11th May 2020 (probably the final 2 interviews).

**Comment by hellais** [comment]
@agrabeli can you make a new issue for those, then, so that we can count this towards the previous sprint.
