### ISSUE TITLE
Footer section title should have larger margin

### ISSUE THREAD

**Issue by sarathms** [ooni/ooni.org#469]
Considering the footer design is almost identical to the one in Explorer, I wanted to point out the spacing between the footer section title and the first link in the section. It would look better and more consistent if the margin between them is larger than the vertical margin between footer links.

![ - 7.png](https://images.zenhubusercontent.com/5defc00b8c6ab2dae53692c4/a46784e8-317d-4529-bffd-9943de5adfa4)

Explorer
![ - 8.png](https://images.zenhubusercontent.com/5defc00b8c6ab2dae53692c4/4d2fc201-1a38-4a0a-ba7d-204f02314ec2)

While at this, we can also ensure the footer links are clickable only on the link text and not the entire block. If using `display: block` then maybe `display: inline-block` will work.

**Comment by hellais** [comment]
Yes you are right, maybe the padding can be a bit tweaked. The reason to increase the margin and padding around the footer elements on the website was that the tap target was too small for being usable on mobile and so I had to increase it to make it work.

I think we should probably do a similar treatment to the footer elements inside of Explorer.

Maybe we should rename this issue as review and align the footer style on all our web resources?

**Comment by hellais** [comment]
This has been implemented here: https://github.com/ooni/ooni.org/pull/485
