### ISSUE TITLE
MM data analysis to support Freedom on the Net report

### ISSUE THREAD

**Issue by agrabeli** [ooni/ooni.org#471]
Community members from Myanmar who are contributing to the annual Freedom on the Net reports are interested in referencing relevant OONI data (if there are censorship findings worth mentioning). 

This involves OONI data analysis for the following time period: **May 2019 to April 2020**. 

In addition to relevant data visualizations, the analysis should also share relevant OONI Explorer measurements that they can potentially link to, as well as an analysis that they can point to (for example, a relevant CSV, a cleaned up version of ipython notebooks, tableau, etc.).

**Comment by hellais** [comment]
This has been done.
