### ISSUE TITLE
Automatically generate binary packages for software

### ISSUE THREAD

**Issue by hellais** [ooni/ooni.org#479]
This epic is to track all work related to automatically building binary software packages

**Comment by bassosimone** [comment]
@hellais, for your consideration: we (and specifically @bassosimone) have not been doing a very good job at tracking the work that should have been put into this milestone. However, I'd like to point out that, as of 2020-08-31:

1. ooni/probe-engine automatically builds the `miniooni` CLI tool at every commit (see [.github/workflows/miniooni.yml](https://github.com/ooni/probe-engine/blob/9e00e6c61db1d8d66692e3acc736763847cc9497/.github/workflows/miniooni.yml))

2. ooni/probe-cli does the same and also runs smoke tests (see [files inside .github/workflows](https://github.com/ooni/probe-cli/tree/770a822fd4f01a7265aa8963250bcd335cfb8b0b/.github/workflows))

It is not fully clear to me whether the scope of this issue also encompass automatically publishing such binaries when we create a new release. If that's the case, then we need to create an issue for that for probe-cli assigned to me(?).

I also wonder whether we want/could do the same for probe-desktop. In such case, there should also probably be here an issue regarding that. But I am not sure about the specifics.

I feel, though, we should either consider this Epic done with what we have or start creating relevant issues in here!

**Comment by hellais** [comment]
I think we need to spend some more time thinking about this problem, I am moving this into Sprint 23 and adding the label discuss.

**Comment by hellais** [comment]
We are closing this in favour of just keeping the debian issue: https://github.com/ooni/probe/issues/1061.

Doing it on desktop is hard and we are not going to do this anytime soon.
