### ISSUE TITLE
Data analysis for student

### ISSUE THREAD

**Issue by agrabeli** [ooni/ooni.org#494]
A student that is interested in using OONI data as part of her thesis has reached out requesting data analysis support. 

Specifically, she wants to know which countries (in South America and Africa) are blocking social media and news websites and which are not. 

**Data analysis requirements**

* **Countries:** The specific list of countries has been shared in a CSV file (more than 60 countries are listed).

* **Data analysis period:** 01.01.2014 - 31.12.2019

* **OONI Probe test:** Web Connectivity

Based on the above, the student has requested a **CSV file** that presents the anomalies for the tested websites. If we can include the **category codes** too (to more easily identify blocked media), that would probably be helpful too.

**Comment by hellais** [comment]
The amount of work required to produce this sort of analysis is not feasible and even if we were to produce some output for this, there is a pretty high chance that it will contain false positives.

With the current data analysis tooling we have available it is a huge undertaking to analysis ALL OONI data from 5 years for 60 countries.

This is more like a month long type project and not something which we can realistically provide easily just to community member like this.

I hope that at some point in the future our tooling will get better and we will have the power to make this multi-month project into something which we can easily do.

I have replied to the student telling them this basically.

I am going for the moment to close this issue as wontfix.
