### ISSUE TITLE
Data analysis for azerbaijan internet watch

### ISSUE THREAD

**Issue by hellais** [ooni/ooni.org#506]
This is about looking into the AZ data and providing an update about it

**Comment by agrabeli** [comment]
@hellais This data analysis should involve AZ measurements collected in April 2020 + May 2020.

**Comment by hellais** [comment]
I did some analysis work on this and started a draft document for the results here: https://docs.google.com/document/d/1-sXAHyWhshXoHh8XplCS9SUpT-RTLlGAEozxe-mp3uw/edit.

Unfortunately the measurement coverage is still very sparse, so we don't have any new existing results to show.

**Comment by hellais** [comment]
I added some more things to the document. I would say this is done. Closing.
