### ISSUE TITLE
Replace images of OONI Probe Mobile with new dashboard design

### ISSUE THREAD

**Issue by agrabeli** [ooni/ooni.org#511]
Currently the OONI website includes images of the OONI Probe mobile app in the following places:

1. Landing page (1st banner): https://ooni.org/

2. Install page: https://ooni.org/install/

3. Mobile Install page: https://ooni.org/install/mobile

As the OONI Probe mobile app has a new dashboard design (following the 2.4.0 release), we need to replace these images with an image that features the latest design.

**Comment by hellais** [comment]
This is implemented in: https://github.com/ooni/ooni.org/pull/667
