### ISSUE TITLE
Create frontend to display URLs in the test-list with the associated priority

### ISSUE THREAD

**Issue by hellais** [ooni/ooni.org#524]
This is about making a UI/frontend which takes data from: https://github.com/ooni/backend/issues/429.

This can be a separate frontend or maybe we should add it as part of OONI Explorer.

**Comment by sarathms** [comment]
@hellais suggested using the [test list API](http://ps1.ooni.io/api/v1/test-list/urls) to get started with the UI work.

**Comment by sarathms** [comment]
Made some good progress with the basic UI function of draggable sorting and generating prioritized list. Here's a preview.

![output.gif](https://images.zenhubusercontent.com/5defc00b8c6ab2dae53692c4/acd74689-0a34-4ba4-a6a1-6b99737f8f4c)

Wondering what to name the repo.

**Comment by sarathms** [comment]
Linking the URL prioritization policy document that I found when searching for something else.
https://docs.google.com/document/d/1wTtgHY3Mz_DgdTTBgSlEEuNdSlDqRSFKQVahdAtclww/edit#

**Comment by hellais** [comment]
We have the frontend running and working.
