### ISSUE TITLE
AZ data analysis

### ISSUE THREAD

**Issue by agrabeli** [ooni/ooni.org#543]
Analyze AZ measurements collected in June 2020.

@hellais In addition, please produce an **updated chart that shows which media websites are blocked in Azerbaijan**, based on data analysis from 1st January 2020 to 30th June 2020. It would be useful if this chart **reflects the blocking and unblocking of media websites within this time range** as well, clearly showing the affected media websites. This chart will be exported (with the OONI logo) and shared with our local partner (so that they can use it as part of their reporting, and as part of a timeline that discusses the blocking and unblocking of media websites in Azerbaijan).

**Comment by hellais** [comment]
This has been done.
