### ISSUE TITLE
Update privacy policy in light of countly

### ISSUE THREAD

**Issue by hellais** [ooni/ooni.org#547]
We should update the privacy policy to mention the fact we are using countly to collect app usage statistics, crash reports and other metadata needed for sending push notifications.

**Comment by agrabeli** [comment]
Take into account previous data policy updates: https://github.com/ooni/ooni.org/pull/555

**Comment by agrabeli** [comment]
@hellais I have updated the OONI Data Policy to discuss our collect of app usage statistics and use of Countly analytics: https://github.com/ooni/ooni.org/pull/555/commits/d81a067767644c28315ebfe484c1d40632e71307

**Comment by agrabeli** [comment]
This is done. We have published the updated version of the OONI Data Policy: https://github.com/ooni/ooni.org/pull/555

See: https://ooni.org/about/data-policy
