### ISSUE TITLE
Update run.ooni.org to avoid confusing desktop users

### ISSUE THREAD

**Issue by bassosimone** [ooni/ooni.org#551]
Linked PR: https://github.com/ooni/run/pull/45

**Comment by bassosimone** [comment]
Maybe @sarathms can double check this in Sprint 17?

**Comment by agrabeli** [comment]
@bassosimone @hellais @sarathms In my latest commit, I have addressed Arturo's feedback: https://github.com/ooni/run/pull/45 Please review so that it can get merged. Thanks.

**Comment by agrabeli** [comment]
This has been merged, but needs to be deployed.
