### ISSUE TITLE
MM data analysis for OTF Fellow

### ISSUE THREAD

**Issue by agrabeli** [ooni/ooni.org#552]
An OTF Information Controls Fellow has been investigating internet censorship in Myanmar over the last year through the use of OONI Probe. They plan to write their final research report in August 2020 based on the findings.

In support of their research, they have requested data analysis support based on the following:

* Country code: **MM**
* Data analysis range: **20/07/2019 (start_date) - 20/07/2020 (end_date)**
* OONI Probe tests: Web Connectivity, HTTP Header Field Manipulation, HTTP Invalid Request Line

Essentially, they would like to know:

* which **websites are blocked** in Myanmar (how the blocking varies across ISPs & which censorship techniques are adopted);
* whether **middleboxes** are detected on tested networks (and if so, whether the vendor is identifiable).

**Data analysis deadline = Friday, 31st July 2020** (so that the fellow can ask questions based on the analysis during the last week of July, before they start writing the report in early August 2020).

Based on this analysis, we will produce:

* **spreadsheet with relevant measurements** that show blocking (and middleboxes) that the fellow can link to in their report;
* **charts** illustrating key findings (that the fellow can include in their report).

Things to take into account:

1. Recent report on censorship events in Myanmar: https://ooni.org/post/2020-myanmar-blocks-websites-amid-covid19/

2. In 2012, OONI measurements showed that BlueCoat was being used on networks in Myanmar

**Comment by hellais** [comment]
I will not be able to take on this task as I am going to be on vacation throughout the Sprint 18. I am going to un-assign myself from this issue.

**Comment by agrabeli** [comment]
@FedericoCeratto do you perhaps have a few spare cycles to work on this..?

**Comment by agrabeli** [comment]
This is done!
