### ISSUE TITLE
Publish & publicize new Partners page

### ISSUE THREAD

**Issue by agrabeli** [ooni/ooni.org#556]
This pertains to: https://github.com/ooni/ooni.org/pull/528

Once the new Partnerships page is finalized (in terms of edits based on partner feedback), I'll publish this page (on 9th December 2020) and promote it on mailing lists and social media.

**Comment by agrabeli** [comment]
This will be publicized in late August 2020, once we've received feedback from each partner.

**Comment by bassosimone** [comment]
(Set priority/high because it seems to block other not-so-low priority stuff, feel free to adjust.)

**Comment by agrabeli** [comment]
We're aiming to publish this page on 9th December 2020.

**Comment by agrabeli** [comment]
Done!

Published here: https://ooni.org/partners

Promoted on OONI social media accounts, mailing lists, and Slack channels.
