### ISSUE TITLE
Prepare and record the “Introduction to network measurements” session for Internews

### ISSUE THREAD

**Issue by hellais** [ooni/ooni.org#595]
I received the contract for us to begin working on this last Friday.

Next steps are:
* [x] Follow up with Hermes admin to have the contract approved and sign it
* [x] Research and prepare slides for the lesson
* [x] Record the lesson
* [x] Upload and share the recorded lesson with Internews

**Comment by hellais** [comment]
Moving to the next sprint, see: https://github.com/ooni/ooni.org/issues/598#issuecomment-688090765

**Comment by agrabeli** [comment]
I have recorded (and uploaded) this webinar.
