### ISSUE TITLE
Review and edit SoW on PT work

### ISSUE THREAD

**Issue by agrabeli** [ooni/ooni.org#604]

**Comment by agrabeli** [comment]
I've addressed Internews' feedback and we're waiting to hear back from them, before we edit the SoW further.

**Comment by bassosimone** [comment]
With @agrabeli we will be revising again the SoW and PT work based on recent feedback ad the beginning of Sprint 24 🤞

**Comment by agrabeli** [comment]
We've received feedback from Internews and we will be revising the SoW further with @bassosimone.

**Comment by agrabeli** [comment]
This is done!
