### ISSUE TITLE
3.2 Create resources to support community engagement activities

### ISSUE THREAD

**Issue by hellais** [ooni/ooni.org#648]
OONI partners serve as leaders who engage their local communities with censorship measurement research and advocacy. During the last OONI Partner Gathering and on many other occasions, our community members have expressed the need for more resources to support their local community engagement activities. We therefore aim to create educational resources that explain OONI tools and methodologies, and how censorship measurement data can support research and advocacy. These resources may include:

* Workshop slides. We will create different sets of workshop slides to tailor to the needs of different training scenarios (depending on the audience and the duration of the workshops). These workshop slides will explain how to use OONI censorship measurement tools and data. We will develop these slides in coordination with community members, who will be encouraged to use them (and adapt them) as part of their workshops. 
* Multimedia. We previously created a short documentary on our research study in Cuba, and we started an OONI Community Interview series. As part of this proposed project, we will create more multimedia -- such as videos and/or animations -- to encourage community participation in censorship measurement research.
* Outreach kit. To support community engagement activities, we will create an outreach kit that we will publish on the OONI website. This will include flyers and other materials that community members can download and print to share at conferences and workshops.

**Comment by hellais** [comment]
Still missing:
* Publication of OONI Explorer user guide;
* Publication of documentation explaining how to interpret OONI data;
* Publication of documentation explaining how to coordinate censorship measurement campaigns;

**Comment by agrabeli** [comment]
We've completed the multimedia (video and animation). We've published many guides and documentation. And we've completed the Outreach Kit (which is now being designed).

**Comment by agrabeli** [comment]
This activity has been completed! We have published numerous new resources over the past months/years.
