### ISSUE TITLE
OONI Probe Desktop 3.1.0

### ISSUE THREAD

**Issue by bassosimone** [ooni/ooni.org#650]
We have released 3.0.4 in Sprint 24 (see https://github.com/ooni/ooni.org/issues/600). Let us do some extra development in Sprint 25 and then let us aim to bless a new release of the Destktop probe some time around the end of Sprint 26. This new version of the probe shall contain any extra improvement that we have been able to merge within the Sprint 25 and Sprint 26 merge windows, plus improvements in the CLI.

**Comment by sarathms** [comment]
We will be releasing 3.1.0 instead. Tracked here: https://github.com/ooni/probe-desktop/pull/184

**Comment by bassosimone** [comment]
Created issue for next release: https://github.com/ooni/ooni.org/issues/693
