### ISSUE TITLE
Host OONI e-booths at Internet Governance Forum (IGF)

### ISSUE THREAD

**Issue by agrabeli** [ooni/ooni.org#657]
As part of OONI's participation at the (online) Internet Governance Forum (IGF), I'll be hosting the OONI e-booths (to provide live consultations to community members) between 2nd - 17th November 2020.

During this sprint, I'll be facilitating 6 hours of OONI e-booths / live consultations.

For more information, see: https://www.intgovforum.org/multilingual/content/igf-2020-village-booth-60-open-observatory-of-network-interference-ooni

**Comment by hellais** [comment]
This is done.
