### ISSUE TITLE
AZ data analysis

### ISSUE THREAD

**Issue by agrabeli** [ooni/ooni.org#668]
In support of Azerbaijan Internet Watch, we will produce a report with the most recent data analysis.

**Country code:** AZ

**Date range:** 1st August 2020 - November 2020 (the latter date will be determined based on the date of the analysis)

**Nettests:** Web Connectivity, WhatsApp, Facebook Messenger, Telegram, Tor, Psiphon

Based on previous analysis/reports, we know that a number of **news media** and **circumvention tool sites** presented signs of blocking.

More recently though (September 2020), the blocking of **social media** was reported in AZ (and OONI measurements seem to corroborate this).

We should therefore pay extra attention to news media, social media, and circumvention tools (in the analysis).

**Comment by hellais** [comment]
I did data analysis for this during the sprint and shared it in the relevant channel.
