### ISSUE TITLE
Start planning OONI partner trainings/gatherings

### ISSUE THREAD

**Issue by hellais** [ooni/ooni.org#746]
Potentially organize and host 2 online OONI Partner Gatherings over 2 weeks. The idea behind splitting this into 2 events is so that we can work with partners based on their timezones.

We could potentially host this in May 2021. The event would involve an OONI training component, as well as workshops that aim to collect partner feedback, communication of needs, joint brainstorming, etc.

This ticket involves the following activities:

- [x] Set dates for 2 OONI Partner Trainings
- [x] Create draft agenda for 3 day event (this will take place twice)
- [x] Send out invitations to all partners

**Comment by agrabeli** [comment]
We will host 2 online OONI Partner Trainings:

1. 24th-26th May 2021 (1pm UTC - 4:30pm UTC)
2. 31st May 2021 - 2nd June 2021 (7am UTC - 10:30am UTC)

Each training will consist of 3 days, with two 1.5 hour sessions in each day (and a 30-minute break in between sessions).
