### ISSUE TITLE
Write Uganda report

### ISSUE THREAD

**Issue by agrabeli** [ooni/ooni.org#752]
In collaboration with our partners, we aim to publish a report on the (increased) censorship events in Uganda leading up to the elections (i.e. access to social media & VPNs was blocked even for users who paid the OTT), as well as on the widespread internet  blackout on election day.

We could distribute efforts as following:

- [x] General writing, editing, and coordination (@agrabeli)
- [x] OONI data analysis + production of charts (@hellais) -- focus on social media + VPN platforms in the week leading up to the elections
- [x] Writing (and analysis) based on experiments (@bassosimone)
- [x] Writing of "internet blackout" section (@agrabeli in collaboration with IODA)
- [x] Other qualitative sections that share context (partners + @agrabeli)

**Comment by agrabeli** [comment]
Written here: https://github.com/ooni/ooni.org/pull/775

**Comment by bassosimone** [comment]
I'm going to double the effort of this issue. Otherwise, my contribution is lost. I think both @agrabeli and I worked for ~13.
