### ISSUE TITLE
Prepare recommended structure of OONI training for SFLC

### ISSUE THREAD

**Issue by agrabeli** [ooni/ooni.org#753]
Our Indian partners, SFLC.in, have requested an OONI training for their staff. We aim to do this during the week of 8th February 2021. They have shared their needs and requirements and based on those, we'll be working on preparing a structure for the training (which we can share with SFLC for approval/feedback).

**Comment by sarathms** [comment]
One point we need to discuss is about their request for training to use probe-desktop. I know that as a matter of policy, they use Linux on their work laptops. And we do not officially support that platform yet.

**Comment by agrabeli** [comment]
Done!
