### ISSUE TITLE
in10: Research on whether to ship the PT as a separate binary

### ISSUE THREAD

**Issue by hellais** [ooni/ooni.org#765]
Narrative report outlining whether the PT should be shipped as a separate binary or whether the OONI Probe engine could direct tor to use itself as a PT, including reporting on opportunities for collaboration with PT developers on how to improve PT testing in the OONI Probe apps.

**Comment by hellais** [comment]
We have done the research for this deliverable, but still need to write the narrative report.

**Comment by bassosimone** [comment]
I wrote the narrative report and @hellais and @agrabeli are providing reviews.

**Comment by hellais** [comment]
The report has been reviewed and is ready for being shared with the funder.
