### ISSUE TITLE
in13: Create beta quality aggregate views of PT data

### ISSUE THREAD

**Issue by hellais** [ooni/ooni.org#768]
Integrate the metrics for pluggable transport test results into the aggregation API

**Comment by FedericoCeratto** [comment]
Average / mean / percentiles / total_count grouped by day and either group-by or filter by probe_cc

**Comment by hellais** [comment]
Support for extracting runtime metrics and exposing them via a new OONI API endpoint has been implemented and deployed on testing. This can be closed.
