### ISSUE TITLE
in14: Create stable aggregate views to support the OONI Explorer dashboard

### ISSUE THREAD

**Issue by hellais** [ooni/ooni.org#769]
Open source production ready code for the aggregation API in support of the interactive OONI Explorer dashboard

**Comment by hellais** [comment]
We have discussed that as part of this we are going to:
* [ ] Add API endpoints for returning stats related to the runtime of PT test results
* [ ] Add an API endpoint which returns the number of metrics for all PT tests grouped by country (this is going to be used by the UI to filter the countries that are selectable)

This is then going to be deployed to backend-fsn.org (which is using clickhouse) and then mapped to the production API via nginx.

**Comment by hellais** [comment]
The listing of number of metrics for all PT tests grouped by country should be a query similar to the following:
```sql
SELECT COUNT(*), probe_cc 
FROM fastpath 
WHERE measurement_start_time > today() - interval '6 months' 
AND (test_name = 'torsf' OR test_name = 'tor' OR test_name = 'stunreachability' OR test_name = 'psiphon' OR test_name = 'riseupvpn')
```

**Comment by FedericoCeratto** [comment]
Related https://github.com/ooni/api/pull/278

**Comment by hellais** [comment]
We have implemented all the backend API endpoints needs to present relevant circumvention tool data in the charts on OONI Explorer: https://explorer.ooni.org/chart/circumvention.

This can be considered done.
