### ISSUE TITLE
blog posts may use special markup to get better snipptets in social media

### ISSUE THREAD

**Issue by darkk** [ooni/ooni.org#78]
It would be nice to see rich snippets for OONI blog posts in facebook/twitter/telegram/whatever.

Facebook has some heuristics to generate rich snippet without special markup, you can see it [here](https://developers.facebook.com/tools/debug/sharing/?q=https%3A%2F%2Fooni.torproject.org%2Fpost%2Fegypt-network-interference%2F), but it's imperfect.

Twitter has no heuristics and just shows the link as-is: https://twitter.com/TheMusta/status/791974185857847296
Twitter also has some process to whitelist domains to be able to generate _twitter cards_. I'm unsure if this process is trivial or not.

[Opengraph](http://ogp.me/) works for facebook/google/telegram and allows to control image/title/text shown in the snippet.
Here are some examples of opengraph markup: https://moz.com/blog/meta-data-templates-123

**Comment by hellais** [comment]
This has been implemented!
