### ISSUE TITLE
Request further legal review of apps + data policy for GDPR compliance

### ISSUE THREAD

**Issue by agrabeli** [ooni/ooni.org#801]
We'll be reaching out to lawyers to request further legal review of the OONI Probe apps and OONI data policy to ensure we're 100% GDPR compliant.

**Comment by jbonisteel** [comment]
I have reached out to the Cyberlaw clinic at Harvard to see if they could help with this.

**Comment by jbonisteel** [comment]
I am going to close this issue otherwise it will be around for a very long time. 

If/when we have any development work to do as related to GDPR, we will open individual tickets as needed (with a more clear scope)
