### ISSUE TITLE
CM data analysis

### ISSUE THREAD

**Issue by agrabeli** [ooni/ooni.org#808]
Our Cameroonian partner is asking which websites have ever been blocked in Cameroon.

From past OONI data analysis, I have only ever seen the following blocked in Cameroon:

* ambazonia.org:
https://explorer.ooni.org/measurement/20181002T170921Z_AS36912_vxZ9pcVg0gUmw3TPzc26LwvUCWGHOwIQ7lc15POfIXYjXs97i8?input=https:%2F%2Fambazonia.org%2F

* ambaland.com:
https://explorer.ooni.org/measurement/20181002T170921Z_AS36912_vxZ9pcVg0gUmw3TPzc26LwvUCWGHOwIQ7lc15POfIXYjXs97i8?input=https:%2F%2Fambaland.com%2F

These sites appeared to have been blocked in October 2018 by means of IP blocking. They haven't been tested much recently though.

While camerounweb.com was reported blocked in February 2019, recent measurements show that it's accessible:
https://explorer.ooni.org/search?until=2021-03-05&since=2021-02-03&domain=www.camerounweb.com&probe_cc=CM

@hellais can you please analyze **CM Web Connectivity measurements** to check:

- Whether the aforementioned sites are currently blocked in Cameroon (and whether we have more measurements on their past blocking)
- Whether other websites are blocked too in Cameroon

Given that the overall volume of Web Connectivity measurements from CM is quite small (in comparison to other countries), perhaps the analysis can include all measurements ever collected?

It would be useful to have OONI Explorer measurements for any blocked sites, as well as a chart (if relevant). Thanks!

**Comment by hellais** [comment]
This is done.
