### ISSUE TITLE
Research on media censorship worldwide

### ISSUE THREAD

**Issue by agrabeli** [ooni/ooni.org#809]
We're starting a research project with the goal of examining **media censorship around the world over the last year**. 

Given that the volume of OONI measurements collected from around the world is very large, we'll potentially be limiting the study to the following 23 countries:

1. Algeria 
2. Azerbaijan 
3. Bahrain 
4. Belarus 
5. Burundi 
6. Cambodia 
7. China 
8. Djibouti 
9. Egypt 
10. Iran 
11. Myanmar 
12. Pakistan 
13. Philippines 
14. Russia 
15. Saudi Arabia 
16. Tajikistan 
17. Thailand 
18. Turkmenistan 
19. Togo 
20. Turkey 
21. UAE 
22. Venezuela 
23. Vietnam
24. Nigeria
25. Yemen

In order to evaluate whether we should in fact focus on the above list of countries, we first need to look at:

- [ ] Volume of (Web Connectivity) measurement coverage per country
- [ ] Whether there are previous reports of media censorship in each country
- [ ] Measurement coverage in terms of news media testing (per country)

We can then evaluate whether we should drop/change/add countries in the list. 

Once we have a finalized list, we need to: 

- [ ] Update the [country test lists](https://github.com/citizenlab/test-lists/tree/master/lists) to ensure that adequate/relevant news media websites are included for testing
- [ ] Encourage further media testing in each country

Once we have enough testing coverage, we can proceed with relevant OONI data analysis and report writing.

**Comment by agrabeli** [comment]
We could also consider *Yemen* as a case study, given that media censorship has been reported there a lot.

**Comment by agrabeli** [comment]
We can also consider adding Nigeria to the list, given that People's Gazette (and a few other media sites) is blocked: https://explorer.ooni.org/search?until=2021-03-05&since=2021-02-03&domain=www.peoplesgazette.com&probe_cc=NG

**Comment by agrabeli** [comment]
I'm not familiar with any media censorship in Togo and Cambodia. Unless we can identify reported cases of media censorship in those countries, I'd suggest dropping them from the list.

**Comment by hellais** [comment]
Here is a chart of the measurement coverage for those countries. I tried to order them loosely based on measurement coverage.
![image.png](https://images.zenhubusercontent.com/58442543b9dc3c622022e97d/53a93984-345b-4cfa-b656-a7c89de7047b)

**Comment by agrabeli** [comment]
This is being deferred to later months for the moment.

**Comment by jbonisteel** [comment]
This is an old ticket and is duplicated by others.
