### ISSUE TITLE
Add link to sentry, countly and google analytics in our data policy

### ISSUE THREAD

**Issue by hellais** [ooni/ooni.org#812]
We should add links to the relevant privacy policies of the platforms we use and update our own data policy based on the outcome of the audit of sentry, countly and google analytics (see: https://github.com/ooni/probe/issues/1399).

**Comment by agrabeli** [comment]
We're no longer using Firebase analytics.

**Comment by agrabeli** [comment]
OONI Data Policy updated here: https://github.com/ooni/ooni.org/pull/838 

We now only use:

* Sentry for crash reports
* Countly for push notifications (Android)
* Matomo for ooni.org visits

In all cases, we link to the websites of these tools in our data policy.
