### ISSUE TITLE
Data analysis for Venezuelan partners

### ISSUE THREAD

**Issue by agrabeli** [ooni/ooni.org#823]
Our Venezuelan partners (IPYS Venezuela) have requested data analysis support.

**Data analysis requirements**

* Country code: VE
* Date range: 2020-01-01 - 2020-12-31
* Nettest: Web Connectivity

Based on the analysis of Web Connectivity measurements collected from Venezuela throughout 2020, please produce:

* CSV file (based on blocked sites, including details of blocking and relevant OONI Explorer measurements)
* Relevant charts on blocked websites

@hellais if you could produce these within the **first 1-2 weeks of April 2021**, that would be amazing. Thank you!

**Comment by hellais** [comment]
This is done.

**Comment by agrabeli** [comment]
We have submitted a chart and CSV file to our partner.
