### ISSUE TITLE
UG data analysis

### ISSUE THREAD

**Issue by agrabeli** [ooni/ooni.org#825]
An Ugandan researcher has requested the following data analysis support:

**Country code:** UG
**Nettests:** Tor, Psiphon, Web Connectivity
**Web Connectivity analysis:** Only for the following domains: thunder.free-signal.com, secure.free-signal.com, speedvpn.app, supervpn.im
**Date range:** 2021-01-09 - 2021-01-29

They have requested 2 charts based on this analysis:

1. Chart based on the testing of Tor + Psiphon in Uganda for the above date range
2. Chart based on the testing of the above domains in Uganda (for the above date range)

**Comment by hellais** [comment]
This has been done.
