### ISSUE TITLE
Add IODA to the OONI Partners page

### ISSUE THREAD

**Issue by agrabeli** [ooni/ooni.org#879]
We have been collaborating with IODA (https://ioda.caida.org/ioda/dashboard) closely over the last years, and they've agreed to be listed on the OONI Partners page: https://ooni.org/partners

**Assets for the new IODA page** (to be listed in the Partners page):

* Name: Internet Outage Detection & Analysis (IODA), CAIDA
* Website: https://ioda.caida.org/
* Scope: Global

**Description:** 

The [Internet Outage Detection and Analysis (IODA)](https://ioda.caida.org/) project is run by the [Center for Applied Internet Data Analysis (CAIDA)](https://www.caida.org/), which is based at the University of California's San Diego Supercomputer Center.

IODA monitors the Internet in near-realtime to identify macroscopic Internet outages affecting the edge of the network, i.e., significantly impacting a network operator (AS) or a large fraction of a country.

IODA combines information from three data sources, establishes the relevance of an event and generates alerts. The outage events and the corresponding signals obtained through automated analysis are displayed on [dashboards](https://ioda.caida.org/ioda/dashboard) and interactive graphs that allow the user to further inspect the data.

OONI and IODA work closely on monitoring and documenting Internet censorship events around the globe.

**Collaboration:**

* Myanmar: Data on internet blocks and internet outages following military coup: https://ooni.org/post/2021-myanmar-internet-blocks-and-outages/
* Uganda: Data on internet blocks and nationwide internet outage amid 2021 general election: https://ooni.org/post/2021-uganda-general-election-blocks-and-outage/
* Iran’s nation-wide Internet blackout: Measurement data and technical observations: https://ooni.org/post/2019-iran-internet-blackout/
* Benin: Social media blocking and Internet blackout amid 2019 elections: https://ooni.org/post/2019-benin-social-media-blocking/
* Internet disruption in Gabon amid coup attempt: https://ooni.org/post/gabon-internet-disruption/

**Comment by albertodainotti** [comment]
Thanks @agrabeli ! 
I would suggest to modify: 
`The outage events and the corresponding signals obtained through automated analysis are displayed on dashboards and interactive graphs that allow the user to further inspect the data.` 
to 
`The outage events and the corresponding signals obtained through automated analysis are displayed in near-realtime on public dashboards and interactive graphs that allow the user to further inspect the data.`.  
I.e., added the realtime and public bits.

(Feel free to "dash" near-real-time however you like :-D )

**Comment by agrabeli** [comment]
IODA's logo is available here: https://ioda.caida.org/bundles/caidacharthousefrontend/images/logos/ioda-logo.svg

**Comment by agrabeli** [comment]
Done here: https://github.com/ooni/ooni.org/pull/884

**Comment by agrabeli** [comment]
IODA page: https://ooni.org/partners/ioda/
